[source.crates-io]
replace-with = "rsproxy-sparse"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[http]
check-revoke = false
multiplexing = false
low-speed-limit = 50
timeout = 120

[net]
retry = 8
